### ISSUE TITLE
[Configuration #24] Support configuration of wrapped optional type

### ISSUE THREAD

**Issue by loganmzz** [loganmzz/macon-rs#27]
When using attributes to configure `Option` support ([documentation](https://docs.rs/macon/1.0.0/macon/#option-fields)), a wrapped type can be specified:

```rust
type Flag = Option<bool>;

#[derive(Builder)]
struct Setting {
  #[builder(Option=bool)]
  quiet: Flag,
}
```

Same thing should be possible from configuration file:

```yaml
option_types:
  includes:
  - Opt           # Using string format, suppose to be generic
  - path: Opti    # Using structured format, no wrapped type specified, suppose to be generic
  - path: Flag    # Using structured format, specify wrapped type
    wrapped: bool
```
